apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgresql
  namespace: argocd
spec:
  project: default
  destination:
    namespace: uat
    server: https://kubernetes.default.svc
  sources:
    - chart: postgresql
      repoURL: https://charts.bitnami.com/bitnami
      targetRevision: 15.5.15
      helm:
        valueFiles:
          - $values/postgres-values.yaml
        values: |
          image:
            repository: bitnamilegacy/postgresql
            tag: 16.3.0-debian-12-r19
          volumePermissions:
            enabled: true
            image:
              repository: bitnamilegacy/os-shell
          metrics:
            enabled: true
            image:
              repository: bitnamilegacy/postgres-exporter  

    - repoURL: 'https://github.com/sopana1301/DB-Testing.git'
      targetRevision: HEAD
      ref: values

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
