apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgresql
  namespace: argocd
spec:
  project: default
  destination:
    namespace: v2qa
    server: https://kubernetes.default.svc
  sources:
    - chart: postgresql
      repoURL: https://charts.bitnami.com/bitnami
      targetRevision: 15.5.20
      helm:
        valueFiles:
          - $values/Databases/postgres-values.yaml

    - repoURL: 'https://github.com/dWise-Healthcare-IT-Solutions-Pvt-Ltd/LT-QA-K8s-Stack.git'
      targetRevision: HEAD
      ref: values

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
