apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgresql
  namespace: argocd
spec:
  project: default
  destination:
    namespace: v2qa
    server: https://kubernetes.default.svc
  source:
    repoURL: 'https://github.com/sopana1301/DB-Testing.git'  # your repo
    targetRevision: main
    path: .                                                  # folder containing app + values
    helm:
      chart: postgresql                                     # chart name from Bitnami
      valueFiles:
        - postgres-values.yaml                               # relative to repo path
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
